--- 
- name: Get Device Facts
  hosts: junos
  gather_facts: no

  vars_files:
   - hosts_vars.yml

  
  tasks:
  - name: Remove user "devuser" login
    junos_user:
      name: devuser
      provider:
        timeout: 100
      state: absent
